name: Update WordPress.org assets

on:
  push:
    branches: [main]
    paths:
      - readme.txt
      - .wordpress-org/**
  workflow_dispatch:

jobs:
  update_assets:
    name: Push readme/assets to WP.org
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
